name: LSE Status Monitor

on:
  schedule:
    # Läuft alle 10 Minuten - zuverlässiger als 5 Minuten
    # GitHub führt sehr häufige Schedules oft verzögert aus
    - cron: '*/10 * * * *'
  workflow_dispatch: # Ermöglicht manuelles Testen

jobs:
  check-status:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4
    
    - name: Check LSE Status
      env:
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        EMAIL_TO_2: ${{ secrets.EMAIL_TO_2 }}
        EMAIL_TO_3: ${{ secrets.EMAIL_TO_3 }}
      run: |
        python check_lse.py
    
    - name: Update status file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add status.json 2>/dev/null || true
        git commit -m "Update status [skip ci]" || true
        git push || true
