name: LSE Status Monitor

on:
  schedule:
    # Mehrere explizite Zeitpunkte statt */10 - das ist zuverlässiger!
    # Läuft stündlich zu diesen Minuten: 00, 10, 20, 30, 40, 50
    - cron: '0 * * * *'   # Jede Stunde um :00
    - cron: '10 * * * *'  # Jede Stunde um :10
    - cron: '20 * * * *'  # Jede Stunde um :20
    - cron: '30 * * * *'  # Jede Stunde um :30
    - cron: '40 * * * *'  # Jede Stunde um :40
    - cron: '50 * * * *'  # Jede Stunde um :50
  workflow_dispatch: # Ermöglicht manuelles Testen

jobs:
  check-status:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4
    
    - name: Check LSE Status
      env:
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        EMAIL_TO_2: ${{ secrets.EMAIL_TO_2 }}
        EMAIL_TO_3: ${{ secrets.EMAIL_TO_3 }}
      run: |
        python check_lse.py
    
    - name: Update status file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add status.json 2>/dev/null || true
        git commit -m "Update status [skip ci]" || true
        git push || true
